### ISSUE TITLE
Add clear:cache after resore

### ISSUE THREAD

**Issue by OleksiiBrylin** [LucaPon/statamic-content-backup#4]
Hey, 
thank you for this addon. 

Could you add clear cache function after restoreBackup function? 
It should prevent inconsistent content issues.

**Comment by LucaPon** [comment]
Hi @OleksiiBrylin,

Thank you for your feedback and I'm glad you like the addon!

I've added the cache clear to the restoreBackup function as you suggested. This should help in preventing any inconsistent content issues after a restore operation.

Please let me know if everything works as expected or if there's anything else I can help with.
